"""adicionado tema preferido ao usuario

Revision ID: 0cc84d2afa98
Revises: 1ff1fda6c18c
Create Date: 2026-09-02 06:34:29.660576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc84d2afa98'
down_revision = '1ff1fda6c18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('nome_usuario', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('cargo', sa.String(length=50), nullable=False),
    sa.Column('pode_cadastrar_paciente', sa.Boolean(), nullable=False),
    sa.Column('pode_montar_cardapio', sa.Boolean(), nullable=False),
    sa.Column('pode_ver_financeiro', sa.Boolean(), nullable=False),
    sa.Column('tema_preferido', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome_usuario')
    )
    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('nome_usuario', sa.VARCHAR(length=50), nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), nullable=False),
    sa.Column('senha', sa.VARCHAR(length=100), nullable=False),
    sa.Column('ativo', sa.BOOLEAN(), nullable=False),
    sa.Column('cargo', sa.VARCHAR(length=50), nullable=False),
    sa.Column('pode_cadastrar_paciente', sa.BOOLEAN(), nullable=False),
    sa.Column('pode_montar_cardapio', sa.BOOLEAN(), nullable=False),
    sa.Column('pode_ver_financeiro', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome_usuario')
    )
    op.drop_table('usuarios')
    # ### end Alembic commands ###
