"""adicionar foto de perfil ao usuário

Revision ID: 11a1b4c46803
Revises: 0cc84d2afa98
Create Date: 2026-09-04 07:10:30.996666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a1b4c46803'
down_revision = '0cc84d2afa98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('foto_perfil', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('foto_perfil')

    # ### end Alembic commands ###
