"""tabelas de antropometria anamnese e planos

Revision ID: 1ff1fda6c18c
Revises: 
Create Date: 2026-09-01 07:25:41.836612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ff1fda6c18c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('idade', sa.Integer(), nullable=False),
    sa.Column('genero', sa.String(length=1), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('altura', sa.Float(), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anamneses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('objetivo_principal', sa.String(length=100), nullable=True),
    sa.Column('patologias', sa.Text(), nullable=True),
    sa.Column('medicamentos', sa.Text(), nullable=True),
    sa.Column('alergias_intolerancias', sa.Text(), nullable=True),
    sa.Column('aversoes_alimentares', sa.Text(), nullable=True),
    sa.Column('qualidade_sono', sa.String(length=50), nullable=True),
    sa.Column('consumo_agua_diario', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultas_antropometricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('data_consulta', sa.DateTime(), nullable=False),
    sa.Column('peso_atual', sa.Float(), nullable=False),
    sa.Column('altura_atual', sa.Float(), nullable=False),
    sa.Column('percentual_gordura', sa.Float(), nullable=True),
    sa.Column('percentual_massa_magra', sa.Float(), nullable=True),
    sa.Column('circunferencia_cintura', sa.Float(), nullable=True),
    sa.Column('observacoes_clinicas', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planos_alimentares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('nome_plano', sa.String(length=100), nullable=True),
    sa.Column('meta_calorica', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('paciente')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('idade', sa.INTEGER(), nullable=False),
    sa.Column('peso', sa.FLOAT(), nullable=False),
    sa.Column('altura', sa.FLOAT(), nullable=False),
    sa.Column('genero', sa.VARCHAR(length=1), nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('planos_alimentares')
    op.drop_table('consultas_antropometricas')
    op.drop_table('anamneses')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
