"""adiciona datas de cadastro e ultimo acesso aos usuarios

Revision ID: 6a6b072d012b
Revises: 11a1b4c46803
Create Date: 2026-09-06 14:24:08.442842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a6b072d012b'
down_revision = '11a1b4c46803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ultimo_acesso', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('ultimo_acesso')
        batch_op.drop_column('data_cadastro')

    # ### end Alembic commands ###
