"""Adicionar campo data de nascimento aos pacientes

Revision ID: dba48115b4d7
Revises: 6a6b072d012b
Create Date: 2026-09-06 21:48:52.212353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dba48115b4d7'
down_revision = '6a6b072d012b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pacientes', schema=None) as batch_op:
        batch_op.drop_column('data_nascimento')

    # ### end Alembic commands ###
